name: start_service
description: A Flutter package for handling start service with policy checks.
version: 0.1.0
homepage: https://github.com/yourusername/start_service

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: